### ISSUE TITLE
Tag WebSocket server metrics with the device ID

### ISSUE THREAD

**Issue by kitcambridge** [mozilla-services/autopush#102]
`SimplePushServerProtocol` only tags emitted metrics with the user agent. It'd be helpful to include the `uaid_hash` and `remote-ip`, too, like we do for `AutoendpointHandler`. The former would help with triaging Bugzilla tickets; the latter with tracking down connection counts per client.

Also, some other metrics we could collect:

- [ ] Whether a `mobilenetwork` field is present in the client hello, indicating the client is on a cellular network. If we wanted, we could break this down by carrier, too—`mobilenetwork["mcc"]` and `mobilenetwork["mnc"]`.
- [ ] Malformed and incomplete messages that call `bad_message`.
- [ ] Whether the client was already connected (break down by local vs. remote).

**Comment by bbangert** [comment]
Unclear how actionable this data is, or what metric graphs this data will support.
