### ISSUE TITLE
Migrate from snaek to milksnake

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/autopush#1045]
snaek was recently deprecated for milksnake. It continues to function for us in its current form but it's unlikely to be maintained going forward. At some point we should migrate to milksnake -- it is a lower level solution than snaek though, so it appears to it'll require some tweaking.

Some more information on milksnake: https://www.reddit.com/r/rust/comments/744mjw/milksnake_a_new_approach_for_rust_and_python/

**Comment by pjenvey** [comment]
the deprecated snaek is still working for now, but one benefit from switching to milksnake:

snaek hardcodes the slower "cargo build --release" command when creating the cffi lib via setup.py. Whereas milksnake makes you define your build command in setup.py: we could easily toggle building a release vs a quicker non-release build, improving autopush_rs's current development cycle (especially w/ its reliance on test_integration_rs)

**Comment by pjenvey** [comment]
I have a WIP branch over at https://github.com/mozilla-services/autopush/tree/feat/1045 but this is blocked on what looks like a cbindgen bug https://github.com/eqrion/cbindgen/issues/131

**Comment by bbangert** [comment]
Closing this as we will likely switch entirely to Rust in Q2 or not far beyond.

**Comment by pjenvey** [comment]
reopening because:
- snaek's cbindgen is very old, which can be limiting. e.g. it won't parse nested import groups (unfortunately, neither does the latest cbindgen https://github.com/eqrion/cbindgen/issues/164 but at least now there's a chance of a later version fixing it that we could use)
- allows toggling the rust build into debug mode easily. handy for local devel and potentially for CI
