### ISSUE TITLE
Transition to new router table that uses TTL instead of rotation

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/autopush#1051]
Convert autopush to use a TTL based router table to reduce DB writes. 
requires #1049

**Comment by jrconlin** [comment]
Blocked on #1081

**Comment by bbangert** [comment]
Closing this as we've agreed to not move the router table, merely to add TTL's to the existing table and begin using them in the future. Separate bugs addressing that should be made for the new quarters goal of moving Push to maintenance only.
