### ISSUE TITLE
Wrap all known routing failures with a Metric call

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/autopush#1052]
External routing can fail. Now that we have some production candidate errors in sentry, wrap the calls with a metric so we can monitor via dashboard.

https://sentry.prod.mozaws.net/operations/autopush-prod/issues/605720/

https://sentry.prod.mozaws.net/operations/autopush-prod/issues/605720/

**Comment by pjenvey** [comment]
and https://sentry.prod.mozaws.net/operations/autopush-prod/issues/605719/
