### ISSUE TITLE
Add a UDP wake-up bridge

### ISSUE THREAD

**Issue by kitcambridge** [mozilla-services/autopush#106]
Client bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1157696

Now that @bbangert's fantastic routing refactor has landed, we can add a separate bridge for the TEF [UDP wake-up platform](https://github.com/telefonicaid/wakeup_platform). Unlike our other bridges, this one only sends a signal for the client to reconnect if it's offline.

It works like this:

* When the client connects to the push server, it opens a UDP port and includes the IP, port, and carrier info in the [handshake](https://github.com/mozilla/gecko-dev/blob/master/dom/push/PushServiceWebSocket.jsm#L1108-1121): `{"messageType":"hello","uaid":"","channelIDs":[],"wakeup_hostport":{"ip":"127.0.0.1","port":65535},"mobilenetwork":{"mcc":"001","mnc":"01","netid":"001-01.default"}}`. We'll store these params for the wake-up request.
* If the server supports UDP wake-up, and the connection idles for [10 seconds](https://github.com/telefonicaid/notification_server/blob/v1.3/src/ns_ua/connectors/ConnectorUDP.js#L48-50), the server closes the WebSocket with a special close code (4774). The client [won't reconnect](https://github.com/mozilla/gecko-dev/blob/master/dom/push/PushServiceWebSocket.jsm#L1230-1235) when it receives this close code.
* When the push server wants to wake up a client, it sends an HTTP request to the TEF wake-up server (authenticated with a TLS client cert issued by TEF).
* The TEF wake-up server sends a UDP packet to the client, which [prompts the client to reconnect](https://github.com/mozilla/gecko-dev/blob/master/dom/push/PushServiceWebSocket.jsm#L1287-1288) to the push server.

If we see a client isn't online, we can just store the message, and send the ping afterward. The client will get that message the next time it reconnects.

**Comment by jrconlin** [comment]
Patch in progress: https://github.com/mozilla-services/autopush/tree/feature/udp

(Currently trying to figure out why local test passes, but travis blows up.)
