### ISSUE TITLE
Timeout when sending push notification to updates.push.services.mozilla.com

### ISSUE THREAD

**Issue by steffenweber** [mozilla-services/autopush#1071]
We have about 100 Firefox users that are subscribed to our push notifications. We regularly see that some of our requests to https://updates.push.services.mozilla.com/wpush/v1/... timeout. Curl says `Connection timed out after 15000 milliseconds` (I've already increased the timeout from 5 seconds which has not helped).

We use HTTP Keep-Alive to reuse a single TCP connection for all ~ 100 POST requests and to keep resource usage as low as possible. But as I said, some requests cause a timeout.

I suspect that there might be a rate-limit enforced by the Mozilla servers such that they just stop responding temporarily if the rate-limit is exceeded. Could you please let me know how many requests per time interval are deemed acceptable such that we can adjust our code?

**Comment by jrconlin** [comment]
As an update: We're still not quite seeing what you've seen so still a bit stumped why you're getting those. We have a number of changes lined up for the new year which may impact delivery so it might be good to check again once a new version is pushed to production.

**Comment by steffenweber** [comment]
We did not have any issues in the past ~ 2 or maybe even 3 weeks. I'll let you know when the problem reappears.

**Comment by steffenweber** [comment]
I've justed noticed the issue again at 2017-12-11 between 14:00:18 and 14:02:03 UTC.

`Connection timed out after 15001 milliseconds`

**Comment by jrconlin** [comment]
First off: thanks for that timestamp, it's a huge help.

Second: Oddly, I'm not seeing any weirdness in our metrics. There was a burst of latency around 1100 UTC that was about 40% higher, but at 1400, it was pretty calm on our end. I'm wondering if this might be something far outside of our monitoring. 

Unfortunately, this is the end of a company all hands week (so I know we've not done anything to the servers this week), but I'll see what extra information our ops team might be able to find. 

Thanks again!

**Comment by oremj** [comment]
@steffenweber What IP or IP block are you making requests from? I can look in to some specific requests. Thanks.

**Comment by steffenweber** [comment]
The IP address is 87.230.75.2 (www.computerbase.de).

**Comment by bbangert** [comment]
Are these delays still occurring? Also, are they using keep-alive connections?

**Comment by steffenweber** [comment]
I cannot remember exactly whether the problems are completely gone but the situation has definetely improved.

Yes, I'm using keep-alive.

**Comment by bbangert** [comment]
Ah, so, one of the reasons I mention keep-alive is that its possible the keep-alive connection is in fact dead and you're experiencing a client-side timeout before its detected. Our servers have more aggressive TCP keep-alives that may have dropped the connection on our side that your sending code didn't notice. That would also explain why it's not consistent, as it'd only occur under cases where the connection dropped but the client failed to detect it faster.

**Comment by steffenweber** [comment]
Our push notifications are indeed sent by long-running background workers. Maybe there was some longterm connection reuse happening behind the scenes. I've now changed their code to explicitly close the keep-alive connection after each batch.

I'll close this issue and comment again should the issue return. Thank you for your help!
