### ISSUE TITLE
fix ctrl-c not working under autopush_rs

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/autopush#1090]
Currently autopush_rs doesn't correctly handle SIGINT to quit the process. Ideally it would be joining on all the worker threads -- but thread join blocks signal handling.

We may need to make a busy loop in the main python thread to handle receiving the signal and triggering shutdown -- not ideal but I'm not sure there's another option. I think Python 3 may have some improvements for this situation

**Comment by bbangert** [comment]
Note that this will also need to update the sentry code to track the thread handle and join it on shutdown as well.
