### ISSUE TITLE
Abuse Mitigation Bug

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/autopush#110]
Meta bug for dealing with detecting and preventing system abuse. 

Abusive behaviors may include:
* Excessive channel registrations
* Excessive UAID registrations
* Excessive posts to invalid or inactive UAID/Channels

**Comment by jrconlin** [comment]
Feel free to don your darkest hat and think of other ways that this system could be abused. Some may not be resolvable (e.g. botnet controller. You could do the same using encoded twitter posts.)

**Comment by bbangert** [comment]
This has been split out into several other issues to address these individually.
