### ISSUE TITLE
cleanup test_main's resource usage

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/autopush#1106]
test_main doesn't clean up after itself and leaves resources hanging around after the tests, which can easily cause trouble elsewhere in the test suite (e.g. test_rs_integration, test_ssl)

Many of the tests target argument parsing and could be changed to call AutopushConfig.from_argparse, checking for InvalidConfig exceptions. Other tests and possibly main() itself could be improved to avoid the resource leaking.

There's also some db tests in there that probably don't belong any longer.

**Comment by pjenvey** [comment]
RustConnectionApplication could probably use some additional testing as part of this issue to remove its pragma: nocover's

**Comment by bbangert** [comment]
Obsolete per Rust move this year.
