### ISSUE TITLE
Consider user agent differences in autopush_rs

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/autopush#1121]
The port to rust switches user agent parsing from python's ua_parser to the woothee parser. These libs don't produce the exact same results in all circumstances, e.g. "Mac OS X" vs woothee "Mac OSX", "Other" vs "UNKNOWN".

The slight differences will affect metrics and logging aggregates, some may be more important than others or maybe we don't care that much at all.

**Comment by bbangert** [comment]
I'm going to consider this a non-issue, as they can be resolved in the SQL queries without the hassle of a separate fork.
