### ISSUE TITLE
Add a server backoff protocol

### ISSUE THREAD

**Issue by kitcambridge** [mozilla-services/autopush#113]
If the server is overloaded, it'll be helpful to have a way to tell the client to go away and reconnect later. https://bugzilla.mozilla.org/show_bug.cgi?id=1184278 tracks the client work to support this.

**Comment by bbangert** [comment]
Currently the server will just drop the connection without completing if its overloaded. This should be interpreted by the client as a sign to reconnect with a backoff (and hopefully get a different IP).

**Comment by bbangert** [comment]
Given the websocket handler will backoff already, means that behavior should already be sufficient.
