### ISSUE TITLE
boto3 refactoring

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/autopush#1142]
There's some easy code cleanup around boto3 we should make:

- checking exception codes should have a helper function
- and following that, we could be checking against static strings to avoid typos (maybe we can use an enum backport?)
- creating ClientErrors for tests could probably use a helper function?
- our db interface could probably be rethought a bit now but I'll leave that for an entirely different issue

**Comment by pjenvey** [comment]
According to: https://stackoverflow.com/questions/33068055/boto3-python-and-how-to-handle-errors boto3 "has begun to expose service exceptions on clients (though not on resources)".

Using these would be a good improvement for #1 and #2 above (and maybe 3) over the generic ClientError. Though I'm unsure about the "though not on resources" part. This feature seems to still be undocumented (JR had originally used some of these exceptions but they were removed with them being documented in the first place)

**Comment by bbangert** [comment]
Obsolete per Rust move this year.
