### ISSUE TITLE
include Cargo.toml/lock version bump in release process

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/autopush#1251]
Our release doc (and my script) should bump the version in Cargo.toml and Cargo.lock alongside `__init__.py`. It probably needs to run `cargo update -p autopush` for the lock file.

Not terribly important but it is referenced in the log output

Also the line "git push --tags origin release/{major}.{minor}" shouldn't include --tags: this pushes all tags

**Comment by bbangert** [comment]
Closing as there is no longer about to be a Cargo.toml/lock. This should likely be handled in the new autopush_rs repo.

**Comment by bbangert** [comment]
Also, our release doc needs to reflect that we have a separate repo with the Rust version.

**Comment by bbangert** [comment]
Going to re-open this until we properly log the needed issues.

**Comment by jrconlin** [comment]
Removing the P1 tag since the critical elements have been done.

**Comment by bbangert** [comment]
Obsolete.
