### ISSUE TITLE
Add docker image info to upload to hub

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/autopush#1264]
The current [`mozilla/autopush`](https://hub.docker.com/r/mozilla/autopush/) image on docker hub is sadly lacking any detail about what it is, where to get more info, etc.

**Comment by pjenvey** [comment]
How do we edit it, does oremj have to do it?

**Comment by jrconlin** [comment]
I have no idea, other than it's the responsibility of whoever owns the account for "mozilla" on docker. We should probably file a proper bug once we figure out what data we want to put on there. (this is more a placeholder for Waffle.)

I'll write up something tomorrow or so.

**Comment by jrconlin** [comment]
Bugzilla ticket: https://bugzilla.mozilla.org/show_bug.cgi?id=1470544

**Comment by pjenvey** [comment]
resolved fixed in the bugzilla ticket
