### ISSUE TITLE
Send last-modified date for stored messages

### ISSUE THREAD

**Issue by kitcambridge** [mozilla-services/autopush#127]
From the Web Push spec, section 7.2:

> Push messages that are stored and not delivered to a user agent are delivered when the user agent recommences monitoring. Stored push messages SHOULD include a Last-Modified header field (see Section 2.2 of [RFC7232]) indicating when delivery was requested by an application server.

**Comment by bbangert** [comment]
Closing as this is a SHOULD that isn't really exposed to the DOM anyways.
