### ISSUE TITLE
Move adaptive pings to the server

### ISSUE THREAD

**Issue by kitcambridge** [mozilla-services/autopush#128]
Per Martin's suggestion, let's remove the adaptive ping logic from the client, and have the server drive it.

More folks are running into issues with data usage: https://bugzilla.mozilla.org/show_bug.cgi?id=1189729

**Comment by bbangert** [comment]
For the moment we've decided to use a 5 min websocket ping, any ping more frequent than 50 seconds drops, anything else is allowed. Later, with better operational data, we'll be able to implement adaptive pings.
