### ISSUE TITLE
Rewrite push endpoint into Rust

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/autopush#1305]
In order to reduce costs for endpoint operations, we should rewrite the endpoint/bridge system in rust.

**Comment by pjenvey** [comment]
For reference, the older (application-services) high level tracking issue for this: https://github.com/mozilla/application-services/issues/1182

**Comment by jrconlin** [comment]
closing for https://github.com/mozilla-services/autopush-rs/pull/189
