### ISSUE TITLE
Investigate invalid subscription update message.

### ISSUE THREAD

**Issue by tublitzed** [mozilla-services/autopush#1352]
jon.almeida is suddenly seeing an issue where autopush is returning an invalid subscription update message when trying to connect the Reference Browser to Autopush (this is using the WebPush Rust Component I built in H1 2019) I'm not sure why he's suddenly seeing this error pop up, since it was tested and working before. Web push support in Reference Browser is needed for pairing, send tab, and a few other functions.

-- pulled latest autopush and app-services component, compiled and ran the push example end-to-end test and all worked fine. Really at a loss for why he's seeing this error. (I need the FCM application token in order to test against production, and I don't have that.)

(via JR)^

**Comment by jrconlin** [comment]
1.54 altered the config options, and the instructions to ops were dropped. 

https://bugzilla.mozilla.org/show_bug.cgi?id=1586382 includes the correct configuration.

https://github.com/mozilla-services/autopush/issues/1353 filed to modify the release steps to prevent this from happening again (hopefully)
