### ISSUE TITLE
docker-compose up doesn't work acause of wrong versioned libjemalloc

### ISSUE THREAD

**Issue by dibby-dibby** [mozilla-services/autopush#1379]
docker-compose.yml uses peopleperhour/dynamodb image for dynamodb, but this docker image is not updated and causes the next error

`Building autoendpoint
Step 1/9 : FROM pypy:2-7.3.0
2-7.3.0: Pulling from library/pypy
7e2b2a5af8f6: Pull complete
09b6f03ffac4: Pull complete
dc3f0c679f0f: Pull complete
fd4b47407fc3: Pull complete
b32f6bf7d96d: Pull complete
82411da199e9: Pull complete
fa04e01aa6d0: Pull complete
69ab39dc1561: Pull complete
Digest: sha256:67d5f3e7880616d799300c14e68ba45fb972c05ed3c5295077ee864d5de26ea0
Status: Downloaded newer image for pypy:2-7.3.0
 ---> a90aef2083bd
Step 2/9 : RUN mkdir -p /app
 ---> Running in 11fe7ede1328
Removing intermediate container 11fe7ede1328
 ---> 02dc430386a6
Step 3/9 : ADD . /app
 ---> 4c758f641682
Step 4/9 : RUN chmod +x /app/entrypoint.sh
 ---> Running in fd8724942b3c
Removing intermediate container fd8724942b3c
 ---> 646d34daa97d
Step 5/9 : WORKDIR /app
 ---> Running in 3f4d5830d0ec
Removing intermediate container 3f4d5830d0ec
 ---> 8299392982c8
Step 6/9 : ENV PATH=$PATH:/root/.cargo/bin
 ---> Running in b617c3228914
Removing intermediate container b617c3228914
 ---> d0055de260b7
Step 7/9 : RUN     apt-get update &&     apt-get install -y -qq libexpat1-dev gcc libssl-dev libffi-dev libjemalloc1 &&     make clean &&     pip install -r requirements.txt &&     pypy setup.py develop
 ---> Running in 579a8a3958e1
Get:1 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:2 http://security.debian.org/debian-security buster/updates/main amd64 Packages [187 kB]
Get:3 http://deb.debian.org/debian buster InRelease [122 kB]
Get:4 http://deb.debian.org/debian buster-updates InRelease [49.3 kB]
Get:5 http://deb.debian.org/debian buster/main amd64 Packages [7907 kB]
Get:6 http://deb.debian.org/debian buster-updates/main amd64 Packages [7380 B]
Fetched 8338 kB in 30s (278 kB/s)
Reading package lists...
E: Unable to locate package libjemalloc1
`

because there is no libjemalloc1. the current version is libjemalloc2

**Comment by tublitzed** [comment]
resolved via https://github.com/mozilla-services/autopush/pull/1385
