### ISSUE TITLE
Spotty push notifications delivery on iOS

### ISSUE THREAD

**Issue by eoger** [mozilla-services/autopush#1383]
I've noticed some Push notifications sent from the FxA servers never seem to arrive on iOS on a regular basis. We've investigated on the FxA side and it looks like Autopush is returning an error (we *think* a 502) calling the Push endpoint, but we didn't get more information.

From the slack conversion on #push, some errors were logged but couldn't get serialized to a string:
`"message": "Uncaught exception in write_error: "`

**Comment by jrconlin** [comment]
Will contact you offline, but I'm going to need a few things to diagnose what's going on here. 

If possible, could you provide:
Sample message content for a notification.
if this is prod or stage
potentially some APNs credentials so I can test this outside of some sandbox type application, etc.

**Comment by eoger** [comment]
This is happening on prod. I've sent you my test app by email. Thanks for looking into this!

**Comment by scheinercc** [comment]
Could this be related? https://github.com/mozilla-mobile/fenix/issues/8582

**Comment by jrconlin** [comment]
@scheinercc I don't believe so, since the bridge system for FCM is different than for iOS, we generally detect unregistered users better. Still #1415 may help address any similar problem if it's present.
