### ISSUE TITLE
Ensure that update-token does not delete or alter existing subscriptions for UAID

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/autopush#1397]
Getting a report that one of the possible reasons for FxA Send Tab failures happening on android may be that 

1. FxA reports a push publish error
2. Push on android deletes the native FCM token, and requests a new one.
3. The new FCM token is sent to the Push Component via `PushManager(...).update(...)`
4. UA eventually calls `PushManager(...).verify_connection(...)` which results in the server returning no subscriptions for the user. 

We should ensure that UAID is not altered and the subscriptions are not dropped on a FCM token update. We may also need to file an additional bug against the Android Components Push Module if we think the problem might be in the hand-off.

**Comment by jonalmeida** [comment]
This issue seems to be closed, but it's unclear to me what the next steps are. It looks like there were some tests linked to it being closed.

**Comment by jrconlin** [comment]
Basically, it's adding proof that the server is not altering the route data whenever a new vendor token is sent. This ensures that the problem is not with the `update` path.

In essence, it's reducing the number of unknowns.

**Comment by jonalmeida** [comment]
That sounds fair. Should I file an issue in app services then as the next step to investigate? We're still seeing the issue for the Android consumers.

**Comment by jrconlin** [comment]
Yes. I'm *hoping* that fixing the metric tagging issue helps resolve some of this as well, but for now, it's still very much a mystery.
