### ISSUE TITLE
Coalesce blank notifications

### ISSUE THREAD

**Issue by kitcambridge** [mozilla-services/autopush#140]
If an app server sends consecutive blank messages while the client is offline, we should just roll them up into a single notification. No sense in storing and delivering multiple updates that only say, "Something happened!"

OTOH, this is probably a premature optimization. I have a feeling most folks will send data.

**Comment by bbangert** [comment]
Unfortunately, its not even an optimization since it means we'll need to scan the users entire notification row to see if there's another item of the same channel, but no data. Cheaper to just store another one.
