### ISSUE TITLE
Subscription expiration

### ISSUE THREAD

**Issue by kitcambridge** [mozilla-services/autopush#144]
Web Push subscriptions can specify their expiration time via the `Cache-Control` header. Upon expiry, the client sends a `pushsubscriptionchange` event to the service worker, allowing it to request a new subscription.

* As @bbangert points out, if the subscription URL and public key are compromised, we don't want to let senders pester their users indefinitely. Depending on the contents of the message (e.g., if it contains a URL for the worker to open via `Clients.openWindow`), this could open our users to phishing attacks.
* We'd like to encourage listening for `pushsubscriptionchange`, because the worker won't ever receive any more notifications if it doesn't resubscribe.

IIRC, APNS registrations last for two years, and I don't think GCM has a fixed lifetime. We'd need to choose an appropriate interval.

**Comment by bbangert** [comment]
Implementation wise, I can think of a semi-elegant way. We drop in an 'expiration notification' that we deliver to the client, and the client ack's it as usual, but then acts on it as an expiration of a subscription.

**Comment by kitcambridge** [comment]
We discussed this at the standup, and agreed the client should be in charge of expiring subscriptions. The server shouldn't enforce a maximum lifetime, because this creates unnecessary churn for application servers when the subscription URL changes.

**Comment by jvehent** [comment]
This came up during the [risk review](https://bugzilla.mozilla.org/show_bug.cgi?id=1219388). Is there a tracker to implement the endpoint rotation in the client?
