### ISSUE TITLE
`verify_connection` appears to be returning an empty list for users with active subscriptions

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/autopush#1442]
See https://github.com/mozilla/application-services/issues/3314#issuecomment-712380496

Verify that users, particularly mobile users, channels are being registered correctly and are returned as part of the `verify_connection()` call. This is impeding work and analysis on Send Tab reliability.

**Comment by rfk** [comment]
Ref https://github.com/mozilla/application-services/issues/3314#issuecomment-713190223, I think that the server may be returning registered channels in cases where the client expects it to *not*, rather than not returning channels when the client expects that it should.

**Comment by jrconlin** [comment]
I'm not sure how this might happen, unless either the unsubscribe call failed for a given ChannelID and the client did not handle it properly, or if there might be some race condition where the unsubscribe was still pending and a verify was submitted. 

We have a number of both unit and integration tests that check to ensure that a given channel is removed, while other channels remain in tact, during an unsubscribe. Still, chaos is ever present. I'm just not quite sure how to pursue this on the server.

**Comment by jrconlin** [comment]
De-prioritizing this bug since no work is currently required for the autopush server.

**Comment by rfk** [comment]
Based on discussion in the linked appservices issue, I believe the server is behaving as expected here.
