### ISSUE TITLE
Max channels/subscriptions per user

### ISSUE THREAD

**Issue by bbangert** [mozilla-services/autopush#146]
Add a maximum allowed channels/subscriptions per user. This check should likely be done during channel register, and if a limit is exceeded, then an error is returned.

**Comment by kitcambridge** [comment]
It'd be great to convey this limit in the handshake reply, like [GitHub does](https://developer.github.com/v3/#rate-limiting). A smart client could use this to evict stale subscriptions before reaching the limit.

**Comment by bbangert** [comment]
Agreed on the handshake, we can add it to the hello so that the client can use it. It can be an option to set in the autopush config.

**Comment by jrconlin** [comment]
resolved
