### ISSUE TITLE
Sending 100 ChannelIDs during a register message causes the server to abruptly close connection

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/autopush#151]
This may be the root of https://bugzilla.mozilla.org/show_bug.cgi?id=1189729, or it may just be another bug.

Tweaking the smoketest to send 10 UUIDs in the ChannelIDs succeeds, sending 1000 causes the connection to be suddenly terminated.

This may be the websocket library, or JSON parser blowing up because of a buffer allocation problem. Need to investigate work arounds, since clients will be sending LOTS of channelIDs. (Clients can discard and fetch new ChannelIDs if a new UAID is sent to them.)

**Comment by jrconlin** [comment]
An interim fix is to increase the max_message_size for cyclone. 

A proper fix is to prevent the Client from including ChannelIDs as part of the incoming Hello message, since the server ignores them anyway. This will reduce data requirements and speed up push connections as a nice benefit.

**Comment by kitcambridge** [comment]
Fantastic find, JR! :tada:

**Comment by bbangert** [comment]
Closed by the PR.
