### ISSUE TITLE
Set UTF-8 decoding to "ignore"; resolve UnicodeDecodeError exceptions

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/autopush#180]
https://sentry.prod.mozaws.net/operations/autopush-prod/group/101610/

Enforcing strict UTF-8 decoding forces the connection to close. This may penalize users who are on buggy browsers. Instead we should set UTF-8 parsing to "ignore" and drop bad characters silently. 

(If it's possible to log these types of events without impacting delivery to users, that would be useful.)

**Comment by bbangert** [comment]
Should note, this actually isn't something we can fix directly, as its buried in autobahn code, so autobahn should fix it.

**Comment by bbangert** [comment]
Blocked on https://github.com/crossbario/autobahn-python/issues/533.

**Comment by bbangert** [comment]
Closed by #364.

**Comment by bbangert** [comment]
This has not actually been fixed in autobahn 0.12.1. Still waiting on a new release with it.

**Comment by bbangert** [comment]
0.13 finally fixed this.
