### ISSUE TITLE
Restrict encryption header values

### ISSUE THREAD

**Issue by kitcambridge** [mozilla-services/autopush#188]
webpush-wg/webpush-encryption#1 tightens some of the requirements for the `Content-Encoding`, `Encryption`, and `Encryption-Key` headers.
- `Content-Encoding` can only be `aesgcm128`.
- `Encryption` and `Encryption-Key` can only contain one entry.
- `Encryption` can't contain a `key` param.

We could validate this on the server, and reject invalid messages with a 400.

**Comment by jrconlin** [comment]
+1 for server based rejection. Should be easy to do there.

**Comment by bbangert** [comment]
Depends #379.

**Comment by kitcambridge** [comment]
Here's what we can check and reject on the server:

* Missing `Encryption` header.
* `Encryption` header doesn't have any fields or params.
* `dh` or `salt` param in `Encryption` header is missing, invalid base64url, or has trailing `=`.
* `Content-Encoding` is missing or not `aesgcm` or `aesgcm128`.
* Missing `Crypto-Key` (new aesgcm encoding) or `Encryption-Key` (old aesgcm128) header.
* Optional `rs` in `Encryption` header, if specified, is < 2 (or < 1 for aesgcm128) or > 2^36-31.
