### ISSUE TITLE
WebPush verify_channel code fails to handle empty result

### ISSUE THREAD

**Issue by bbangert** [mozilla-services/autopush#189]
In the _verify_channel code in router/webpush.py:
```python
if channel_id not in result:
```

No check is made to ensure result is not None, which it can and will be should there be no channels at all. This causes an exception to be reported to Sentry.

**Comment by kitcambridge** [comment]
I think this is the same error responsible for #172. But I'm not sure.

**Comment by bbangert** [comment]
If an empty set is returned, that will remedy this issue. Closing.
