### ISSUE TITLE
Allow for secondary endpoint encryption key for key rotation

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/autopush#204]
We currently have a single key for encrypting endpoints. We need to make sure we can rotate to a new key reasonably easily.

*Expected Goals from deployment*

1.  Key rotation should not require server restarts, but may require a keys to be cycled in on a clock (e.g. keys are refreshed every 15 minutes from a central repository like S3) S3 has a very high availability rate, particularly for read processes and can be tightly controlled for access.
2.  A limited number of prior keys would be held. Removal of old keys would be a manual process since it's difficult to determine how to do so programatically. (e.g. low usage keys for things like Find My Device).
3.  To reduce CPU overhead, tokens can self-identify the appropriate key to use. Since there is an existing key which does not preform this self-identification, the old key could be used as a last-ditch token decryption attempt.

**Comment by kitcambridge** [comment]
The easiest way to notify clients is probably to reset the UAID. We could extend the protocol to signal when a subscription is no longer valid, but rotating the Fernet key invalidates all existing endpoints, anyway.

**Comment by jrconlin** [comment]
Expected Goals from deployment
1) Key rotation should not require server restarts, but may require a keys to be cycled in on a clock (e.g. keys are refreshed every 15 minutes from a central repository like S3) S3 has a very high availability rate, particularly for read processes and can be tightly controlled for access.
2) A limited number of prior keys would be held. Removal of old keys would be a manual process since it's difficult to determine how to do so programatically. (e.g. low usage keys for things like Find My Device).
3) To reduce CPU overhead, tokens can self-identify the appropriate key to use. Since there is an existing key which does not preform this self-identification, the old key could be used as a last-ditch token decryption attempt.

**Comment by kitcambridge** [comment]
> To reduce CPU overhead, tokens can self-identify the appropriate key to use. Since there is an existing key which does not preform this self-identification, the old key could be used as a last-ditch token decryption attempt. 

You probably saw this already, but it looks like our crypto library has a [`MultiFernet` class](https://cryptography.readthedocs.org/en/latest/fernet/#cryptography.fernet.MultiFernet) that does something like that. It tries all keys in turn for decryption.
