### ISSUE TITLE
Doc: Note in protocol docs about not sending channelID's

### ISSUE THREAD

**Issue by bbangert** [mozilla-services/autopush#224]
ChannelID's should never be sent in the hello handshake, as they might be too large and cause an RST. This should be documented.

**Comment by kitcambridge** [comment]
For posterity, `channelIDs` were removed in https://bugzilla.mozilla.org/show_bug.cgi?id=1201128 (Firefox 44, FxOS 2.2r).

**Comment by jrconlin** [comment]
Closing as obsolete.
