### ISSUE TITLE
Rate limit unauthenticated senders

### ISSUE THREAD

**Issue by jvehent** [mozilla-services/autopush#226]
Following up on the [risk review](https://bugzilla.mozilla.org/show_bug.cgi?id=1219388), notification senders that do not authenticate their requests should be rate limited, to prevent denial of service of the submission endpoints. Senders that need high volume traffic should be encourage to authenticate.

The sender identity should be logged to help with fraud detection. Rate limits violation should be logged into Heka and follow the standard pipeline.

We could also pin a sender identity to an endpoint on first submission, which would prevent a fraudulent sender from using endpoints that belong to another sender.

**Comment by jrconlin** [comment]
This is assisted by the VAPID elements and the dashboard systems.

**Comment by jrconlin** [comment]
Closed Overcome by Events (VAPID, Partner gateway).
