### ISSUE TITLE
Add error handler for cyclone bits in autopush

### ISSUE THREAD

**Issue by bbangert** [mozilla-services/autopush#229]
I found a recent bug in the cyclone HTTP handler portion of websocket.py lately cause I was cruising through the kibana logs. We don't capture errors in the cyclone handler here, like we do in endpoint.py, since we don't have our own ``write_error`` method in there.

We should copy/adapt the write_error method from endpoint.py into the cyclone handlers in websocket.py.

**Comment by jrconlin** [comment]
resolved by #257
