### ISSUE TITLE
Tag all endpoint requests with a UUID

### ISSUE THREAD

**Issue by kitcambridge** [mozilla-services/autopush#268]
From @rafrombrc:

> it would help w/ data validity checks on the metrics
> right now, say there's a sudden, unexpected spike in the endpoint traffic reported by the metrics processing stuff i'm doing
> it might be what's really happening, or maybe something has gone wrong in the data loading and records are being duplicated
> i don't think i can reasonably tell the difference

Probably makes sense to add this to `AutoendpointHandler`.

**Comment by rafrombrc** [comment]
Thanks for this! Couple of follow-up questions:

* Will the new `request_id` data point automatically start showing up in the endpoint server's log output?
* Any ETA on when this might be deployed?
