### ISSUE TITLE
META: Provide Authorization Token system for Partner Contacts

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/autopush#280]
As we grow, we'll need ways to associate push requests with a source (e.g. Pinterest, Facebook, Twitter, etc.) These associations can provide us with contact information, as well as allow those parties to view dashboard data which may be useful.

See: 
https://mozilla.aha.io/features/PUSHSVC-12
https://mozilla.aha.io/features/PUSHSVC-13

**Comment by bbangert** [comment]
See #325 for the preferred way to store these.

**Comment by bbangert** [comment]
No longer needed as VAPID is now in use.
