### ISSUE TITLE
Add smoke test to test_integration for GCM

### ISSUE THREAD

**Issue by bbangert** [mozilla-services/autopush#296]
GCM only has unit tests at the moment, it'd be good to exercise it more completely in test_integration with a smoke-test to verify all the API commands for it work and fail when they should (ignoring whether GCM delivers it or not).

**Comment by jrconlin** [comment]
This should use the gcm_dryrun at first. It would be lovely to use chrome scripting to attempt end-to-end testing, but no idea if that's plausible or practical (since GCM may auto-throttle on some keys)

**Comment by jrconlin** [comment]
GCM offers "dry-run" tests, which exercise the GCM submission (message format, sender and auth key validation). In addition, resources like https://serviceworke.rs/push-rich.html and https://mozilla-services.github.io/WebPushDataTestPage/ allow for complete end-to-end testing on the clients either manually or with automated test suites.

Building a script based system that uses another method creates a potential that we are testing the system, but not the actual usage.

Closing for now.
