### ISSUE TITLE
docs: clarify how to run and test autopush and its build environment

### ISSUE THREAD

**Issue by groovecoder** [mozilla-services/autopush#308]
While going thru the install & testing docs, I got:

```
ERROR:   pypy: InterpreterNotFound: pypy
```

It seems pypy is required for autopush? Should add it to the install docs. I was able to get it with a simple `brew install pypy` and then tests ran.

**Comment by bbangert** [comment]
The documentation should be updated to reflect that the desired build environment doesn't use system OSX Python, and other versions may bind to an older SSL exhibiting the behavior cited in #309.

Updates should also be made indicating how to use normal Python instead, and symlinking it to pypy (for our eventual change back to it in production).

**Comment by groovecoder** [comment]
In particular, the docs should say how to use python with the appropriate OpenSSL library. Do I really have to re-compile python to make pyOpenSSL use the right version of OpenSSL?

**Comment by bbangert** [comment]
This has all changed and is now obsolete.
