### ISSUE TITLE
Support channel association with a JWT key

### ISSUE THREAD

**Issue by bbangert** [mozilla-services/autopush#326]
Channel subscriptions will allow association with a sender key per:
https://github.com/w3c/push-api/pull/182

Our register command will need updating to support the additional information, and our channel-id scheme of a list of channels may need modification to store an additional crypto key with it.

The endpoint will need an additional check to ensure the sender key validates with the channel key if present.

Depends on: #325

**Comment by bbangert** [comment]
To ease storage requirements and schema changes, a sha256 of the public key should be stored in the endpoint itself. To facilitate this endpoint writing/reading scheme, the endpoint will need a prefix indicating the version of the endpoint encoding. No prefix indicates legacy endpoint generation.

Example:
```
endpoint_url /push/[uaid.hex + ":" + chid.hex]
endpoint_url/push/v1[uaid.bytes + chid.bytes]
endpoint_url/push/v2[uaid.bytes + chid.bytes + sha256(public_key).bytes]
```

The appropriate endpoint verifier is then run for each version.

**Comment by kitcambridge** [comment]
@jrconlin I'll send the subscription key as a Base64-encoded URL string, in the `key` field of the `register` message. Sound good?

**Comment by jrconlin** [comment]
@kitcambridge yep, sounds good to me.
