### ISSUE TITLE
Setup docker build file that runs it all

### ISSUE THREAD

**Issue by bbangert** [mozilla-services/autopush#33]
The current Dockerfile builds just the project, to run either autopush or autoendpoint.

It'd be useful for rel-eng to have a single docker that can be started and 'does it all'. My thought is to add another dockerfile (docker now lets you have additional docker files and specify the name when building), and have it spin up moto, autopush, and autoendpoint, with auto* using the moto daemon for AWS instead of actual AWS.

**Comment by kitcambridge** [comment]
Nice. I like that we don't even need to modify the code; just check in a custom `boto.cfg` with the Moto proxy, and set `BOTO_CONFIG`.
