### ISSUE TITLE
Extend ack/unregsiter websocket API

### ISSUE THREAD

**Issue by bbangert** [mozilla-services/autopush#330]
Extend the websocket API to accept two additional keys in the ack dict, a code and a reason. Both of these should be integers, with the code being the class of additional information, with the reason being a subset.

Initial defined code/reason's:

- 100 (Crypto errors)
    - 1  Decryption failed
- 200 (Quota issues)
    - 1  Excessive Background Notification
    - 2  Excessive Foreground Notifications

The autopush server should log these for use by other services, with the notification version.

**Comment by kitcambridge** [comment]
Sounds good! Maybe we can generalize them to "NACKs" and "unregister reasons," respectively. :bike: :art: :house: The 200 category could include quota exceeded, permission revoked, and explicit `pushSubscription.unsubscribe()` calls.

**Comment by kitcambridge** [comment]
Updated list of status codes: https://bugzilla.mozilla.org/show_bug.cgi?id=1246341#c2

**Comment by bbangert** [comment]
Maybe file a separete issue for these codes to be integrated into the main Push websocket API specs so the extensions are documented.

**Comment by kitcambridge** [comment]
Filed mozilla-services/push-service#31. Also, I wonder if we should log and disconnect Simple Push clients that send nacks, as a confidence check. The version isn't meaningful in that case, and it's likely the client is confused.

Also, now that @ncalexan's Android backend has landed, should we have a similar way to report these codes via the HTTP API?

**Comment by bbangert** [comment]
This was done. Logging handles it.
