### ISSUE TITLE
Don't store TTL=0 messages if a client disappears

### ISSUE THREAD

**Issue by bbangert** [mozilla-services/autopush#332]
As is, when a TTL=0 message comes in, if the client is online we attempt to deliver. In the event the client is believed to be online, but during attempted delivery we later find out the connection is dead, instead of storing the TTL=0 message in storage, it should be dropped.

This just requires a small check in the cleanup code that avoid storing un-acked messages which have definitely expired by now when a client drops its connection.

**Comment by bbangert** [comment]
Wow, my bad, I already avoided doing this in the websocket code at line 455:
```python
                    notifs = filter(lambda x: x.ttl != 0, notifs)
```

Sigh.

**Comment by jrconlin** [comment]
r+
