### ISSUE TITLE
Add /status/health or /heath

### ISSUE THREAD

**Issue by oremj** [mozilla-services/autopush#34]
The /status endpoint is a good starting point. I'd also like an endpoint that does a deeper check. Off the top of my head:
* make sure dynamodb is working

**Comment by oremj** [comment]
If we could get this to do a full cluster check, that would be awesome. I'm thinking let ELB detect up/down based on /status and we'll do a full health check of the service based on /health.

**Comment by bbangert** [comment]
@oremj what would /health show?

**Comment by kitcambridge** [comment]
[`ListTables`](http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_ListTables.html) could work for quickly verifying if DynamoDB is up. Looks like it doesn't count against provisioned throughput limits.

**Comment by oremj** [comment]
@bbangert something like:
```
{"dynamodb": "ok", "somethingelse": "error: description of error"}
```
Since this will be public, we'll have to be somewhat vague about the error descriptions.

**Comment by oremj** [comment]
@kitcambridge since this won't happen often, it will be acceptable to use methods that count against our limits.
