### ISSUE TITLE
feature: Add "location" to the websocket notification message 

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/autopush#348]
Message notifications should include a "location" element that contains the message address of the delivered message. 

as an example:
```
{"messageType":"notification",
  "version": ..., 
  "data": ..., 
  "location": "https://updates.push.services/mozilla.com/m/...", 
  ...
}
```

**Comment by kitcambridge** [comment]
After talking with @bbangert, I don't think this is necessary. I suggested adding the URL to help with debugging, but most developers will see this locally, so it's easy to tell which message caused the failure. The dashboard will show decryption errors in the wild once https://bugzilla.mozilla.org/show_bug.cgi?id=1246341 lands.
