### ISSUE TITLE
Include URL to error details in error messages

### ISSUE THREAD

**Issue by bbangert** [mozilla-services/autopush#354]
The JSON error response should include a URL to link to a fuller explanation of the error for better diagnosis for developers on what went wrong.

The autopush docs should be updated to include appropriate details of each errno and how they can be remedied (or link to MDN docs explaining it).

**Comment by jrconlin** [comment]
https://github.com/mozilla-services/autopush/pull/449 introduces "message" to websocket JSON responses. Once that's landed, I will add pointers to other errors and close this.

**Comment by kitcambridge** [comment]
Very nice! I think it would be helpful to include detailed message URLs for endpoint responses, too.

Firefox can show the WebSocket `message` field in the browser console, but those are likely to be client bugs that aren't actionable by web developers. (Though they're handy for Mozilla folks that set a custom `dom.push.serverURL` pref).
