### ISSUE TITLE
Validate data stored in dynamodb

### ISSUE THREAD

**Issue by bbangert** [mozilla-services/autopush#371]
Data should be validated on the way in and out of dynamodb. If data coming out of dynamodb is invalid (or maybe has a wrong version?), the data should be deleted and operations continue.

If data going in is invalid, it should be caught on the way in.

This would allow us to more easily survive bugs causing a rollback.

**Comment by bbangert** [comment]
Just a note, this might be impossible, because of the various ways we need to manipulate and update data in the db. Ideally all functions working with data from the db should verify their data values before using them.

**Comment by jrconlin** [comment]
We should at least consider dynamodb to be a semi-trusted repo. We should normalize as best we can when drawing data because it's coming from a writable store. This will also impact how fast we can read and store data.

**Comment by bbangert** [comment]
Our test should handle this, not more validation.
