### ISSUE TITLE
Don't say the service is unavailable in errno 202

### ISSUE THREAD

**Issue by bbangert** [mozilla-services/autopush#377]
During deploys, or even in normal operation when a user leaves, we don't clear the node until a message hits. For this, we return a 503 with errno 202. The error returned however says "Service Unavailable". That's quite false, the service is fine, the 503 is intentional and the request should be retried. We should not say the service is unavailable.

**Comment by jrconlin** [comment]
Hrm. the only place we return status=503, errno=202  is 
https://github.com/mozilla-services/autopush/blob/master/autopush/router/simple.py#L110
which notes "Node was invalid", "Retry Request"

Was this bug fixed by another patch?

**Comment by bbangert** [comment]
It's because a 503 has its error message copied into the JSON, and 503 has the raw text "Service Unavailable".

**Comment by bbangert** [comment]
Dupe of #378, closed by #384.
