### ISSUE TITLE
Docs: Update docs to reflect normalized UUID

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/autopush#392]
All UUIDs are normalized to lower case with '-' separators. We need to note that in the docs so that app creators who use the UUID as a string index don't get random failures or unexpected results.

**Comment by kitcambridge** [comment]
Let's also have `process_register` return an error for channel IDs that aren't in that form. I think this would be less surprising than our current behavior, where we accept the ID, but then deliver to the normalized form.

At first glance, I think all we need to do is replace the check here: https://github.com/mozilla-services/autopush/blob/master/autopush/websocket.py#L996-L997 with one that checks `data["channelID"] == normalize_id(data["channelID"])`.
