### ISSUE TITLE
Remove DELETE of messages

### ISSUE THREAD

**Issue by bbangert** [mozilla-services/autopush#404]
The webpush spec has no mention of DELETE, yet we seem to support it. This should be removed.

**Comment by kitcambridge** [comment]
https://webpush-wg.github.io/webpush-protocol/#acknowledge_message

It's used for acks, but an app server could also delete a pending message (assuming it's not delivered first, of course). The examples show the same `Location` URL.

**Comment by bbangert** [comment]
Sure, but this URL in particular is the Location to an app server, not a client. I'm referring to that endpoint. App servers are not supposed to be able to delete messages, no?

**Comment by kitcambridge** [comment]
Good question! In the spec, they're identical. If you search for `/d/qDIYHNcfAIPP_5ITvURr-d6BGtYnTRnk`, the same message URL that's returned to the app server is also used for acks, delivery, and receipts.

Maybe @martinthomson can clarify whether an app server can delete messages using this mechanism?

**Comment by martinthomson** [comment]
There is only one resource.  Either can delete it.

**Comment by bbangert** [comment]
Google doesn't seem to support DELETE, and nothing in the final WebPush specs mention that Application Server SHOULD or MAY use the DELETE call. It's documented purely in the context of a client acknowledging the message. 

I think we should remove this function from our impl unless @martinthomson believes this is still a feature that should be supported by Push Servers (in which case the spec likely needs updating).

**Comment by jrconlin** [comment]
Because time waits for no PR, there may be a good reason to keep this function in place. In theory, when a user deletes their account, the client may send a delete for a given UAID, which would delete the user's records and data here. The data is still unusable to us, since it's all encrypted, but deleting the record would definitely make it inaccessible.
