### ISSUE TITLE
Notifications to unsubscribed users produces ProvisionedThroughputExceededException

### ISSUE THREAD

**Issue by rpappalax** [mozilla-services/autopush#435]
Sending flood of notifications to unsubscribed users produces: ProvisionedThroughputExceededException.

Is it adequate to throw this exception or do we want to handle this in another way?

NOTE:
using ap-loadtester scenario:  notification_forever_unsubscribed

----------------------------------
SENTRY ERROR
----------------------------------

ProvisionedThroughputExceededException 400 Bad request

The level of configured provisioned throughput for the table was exceeded. Consider increasing your provisioning level with the UpdateTable API', u'__type': 

https://sentry.prod.mozaws.net/operations/autopush-stage/group/301644/

**Comment by bbangert** [comment]
Intended error.
