### ISSUE TITLE
Sending notification with bad token causes TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by rpappalax** [mozilla-services/autopush#438]
Replacing a valid token with a random one (of same length) causes Unhandled error

  File "/Users/rpappalardo/git/ap-loadtester/aplt/scenarios.py", line 205, in notification_forever_invalid_tokens
    yield ack(channel_id=notif["channelID"], version=notif["version"])
exceptions.TypeError: 'NoneType' object is not subscriptable

CRITICAL:twisted:Unhandled Error

~~~~~~~
NOTE: 
using ap-loadtester scenario notification_forever_invalid_tokens

**Comment by jrconlin** [comment]
This is a problem in ap-loadtester, Moving bug to https://github.com/mozilla-services/ap-loadtester/issues/47
