### ISSUE TITLE
Add SHA dependency checks

### ISSUE THREAD

**Issue by bbangert** [mozilla-services/autopush#454]
pip now lets us add SHA hashes to dependencies, we should use these:
- https://pip.pypa.io/en/stable/reference/pip_install/#hash-checking-mode

**Comment by pjenvey** [comment]
These can be potentially bothersome but should be worth it. You usually include a hash of the .tar.gz and a platform's .whl, but can include as many as needed

The hashin utility can produce these for us. But I'm piptools' pip-compile could get support for what hashin does soon:

https://github.com/nvie/pip-tools/issues/303

w/ pip-compile you can keep the most bare minimum requirements in a '.in' file (a lot like what you'd have in setuptools requires).

It then version pins everything from it including all the sub dependencies. It mentions in the final requirements file where those sub dependencies are from.

e.g.:
six==1.10.0               # via autobahn, cryptography, pyopenssl, python-dateutil, python-jose, txaio

Then it has a --upgrade feature, which is similar to what pyup provides

**Comment by oberstet** [comment]
You could steel from [this](https://github.com/crossbario/crossbar/blob/master/Makefile#L42) .. using [hashin](https://pypi.python.org/pypi/hashin)

**Comment by pjenvey** [comment]
FYI @oberstet pip-tools actually has support for handling these now (that nvie/pip-tools#303 should be closed out). When be switch to it we'll be gaining the .in file format/upgrading and now the hash support too

**Comment by pjenvey** [comment]
We can't enable hash checks while still using editable url specs (txstatsd and temporarily crytography).

I've pinged txstatsd's lauchpad for a new release.. but will probably have to get in touch with them via some other means

**Comment by pjenvey** [comment]
endpoint still needs it, no?

**Comment by bbangert** [comment]
Aw right, we're still on twisted for the endpoint, doh.

**Comment by bbangert** [comment]
Won't be addressing this as we're moving entirely to Rust soonish.
