### ISSUE TITLE
Validate crypto headers

### ISSUE THREAD

**Issue by kitcambridge** [mozilla-services/autopush#456]
@jrconlin brings up a great point in https://github.com/mozilla-services/autopush/pull/452#issuecomment-215485775:

> They already have several significant hurdles to overcome (encryption, user data management, scaling) and then us rejecting their submission because they included characters that literally signify nothing would certainly put me into a foul mood.

We can also help developers by rejecting invalid or incomplete `Encryption` (and `Content-Encoding`) headers, like we already do for `Crypto-Key`. May as well reject early with an informative error instead of storing and delivering a message that the client will drop immediately.

**Comment by jrconlin** [comment]
+1000

**Comment by bbangert** [comment]
Depends on #379.
