### ISSUE TITLE
Enhancement: Blacklist for public keys

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/autopush#459]
For restricted subscriptions, we should provide a means to reject subscription updates with a given VAPID public key.

**Comment by kitcambridge** [comment]
@jrconlin Could you elaborate a bit, please? I don't know what "reject requests with a given public key" means, but I'm likely missing a lot of context.

**Comment by jrconlin** [comment]
@kitcambridge This is more a task for the server side. The "public key" is the VAPID public key (will edit the original to clarify). 

A concern was raised during a review that we may want to blacklist certain VAPID public keys for subscription updates (e.g. a key was compromised, is abusive, etc.) We should consider blocking those from providing updates. This issue would allow for discussion around such a feature.

**Comment by jrconlin** [comment]
DUPLICATE of #227
