### ISSUE TITLE
Revisit 301 handling for the GCM bridge

### ISSUE THREAD

**Issue by kitcambridge** [mozilla-services/autopush#486]
* The client treats non-200 responses as an error, so maybe we can remove the 301 instead of returning a new sender ID. Alternatively, if it's desirable for the client to change its sender ID or URL, we can make the client respect redirects.
* The `Location` header for the 301 is wrong; for example, `https://updates.push.services.mozilla.com/v1/gcm/965234145045/register` returns a 404. I think we might need to change it to `/registration`?

**Comment by jrconlin** [comment]
Currently only GCM has a senderid. We still need to validate that the client is sending the correct one, but GCM does not make changing the value easy once the client app is running. For now, I'll change this to return a 400
