### ISSUE TITLE
Messages are delivered even if previous ones haven't been acknowledged

### ISSUE THREAD

**Issue by kitcambridge** [mozilla-services/autopush#488]
I just tried connecting and delivering several messages without acking them. Subsequent messages still make it through, even though I didn't ack any of the previous ones. Is this intentional? I was under the impression we write messages directly to storage if the client hasn't acked outstanding ones, but maybe that's not correct.

wscat session:

```
> {"messageType":"hello","use_webpush":true}
< {"status": 200, "ping": 300.0, "messageType": "hello", "env": "prod", "uaid": "f5679e4589a74bf0af153c467905c2d4", "use_webpush": true}
> {"messageType":"register","channelID":"9ae78077-16cc-4940-b94f-297124f01169"}
< {"status": 200, "channelID": "9ae78077-16cc-4940-b94f-297124f01169", "messageType": "register", "pushEndpoint": "https://updates.push.services.mozilla.com/push/v1/gAAAAABXcP88zJpN3X-2Z2EEztxHBaP5dcG73L-Md3O7Picbd37ie61x4ToBjTkgoygjnYeiHMloXQuSeYUHcXv1EguKaj9_MNNNBR6zTKFh9L6zVMNv-wTNaiEyeWjDvvf8DHi0qd6G"}
```

Then, if I run `curl -XPOST https://updates.push.services.mozilla.com/push/v1/gAAAAABXcP88zJpN3X-2Z2EEztxHBaP5dcG73L-Md3O7Picbd37ie61x4ToBjTkgoygjnYeiHMloXQuSeYUHcXv1EguKaj9_MNNNBR6zTKFh9L6zVMNv-wTNaiEyeWjDvvf8DHi0qd6G`, I see:

```
< {"version": "gAAAAABXcP9EZGOsG4N1QR2oemy8I_0ieams0UadNQAGeANbkJzK8DVCALbWbQft1quhGNu8VjlEH9066fbgvJcMJ-JWyiCA21r6O8-WxnSzqAEVqXu0wlhRgX9BBKWe4Dal5kgBEYpeUzOEubBQPvMCZZRIWnOW9cd2hucuZUC1gNVg9MyN6Hs=:", "channelID": "9ae78077-16cc-4940-b94f-297124f01169", "messageType": "notification"}
< {"version": "gAAAAABXcP9FKEwNcFvWxikFw0-AfrsoqUhKesDaHHGO4tUaRorfBy-M6EuqRyptLEkQjNYFWc1yulHqVPeoGv-clnj5SZ7DmR7IXCTRgdeGk81SpVT2sX2INGW9Mu0_qljLoXzd8panoJhKnPHl0dt5U_tXCS-bmxOiPKSSgXiLrnUQEJ3qxAw=:", "channelID": "9ae78077-16cc-4940-b94f-297124f01169", "messageType": "notification"}
< {"version": "gAAAAABXcP9Hl71MTQue8IIPyuoz0okNDa_apzcr7uDJYa7JRSJgVT5LxrmVN0IkhtzoFcm7Mcc9PCbhtYizMPtdzC7U9iOBC-nq31u2pw1Uqw2f26ng-E5nNIFn9uZklJy3cFQiNrTmwXN_c5ZlnMmJkhpVBCB-hpcEwRJN2yFqYjtOwx-UKqs=:", "channelID": "9ae78077-16cc-4940-b94f-297124f01169", "messageType": "notification"}
```

The second (`gAAAAABXcP9FKEwNcFvWxikFw0-AfrsoqUhKesDaHHGO4tUaRorfBy-M6EuqRyptLEkQjNYFWc1yulHqVPeoGv-clnj5SZ7DmR7IXCTRgdeGk81SpVT2sX2INGW9Mu0_qljLoXzd8panoJhKnPHl0dt5U_tXCS-bmxOiPKSSgXiLrnUQEJ3qxAw=:`) and third (`gAAAAABXcP9Hl71MTQue8IIPyuoz0okNDa_apzcr7uDJYa7JRSJgVT5LxrmVN0IkhtzoFcm7Mcc9PCbhtYizMPtdzC7U9iOBC-nq31u2pw1Uqw2f26ng-E5nNIFn9uZklJy3cFQiNrTmwXN_c5ZlnMmJkhpVBCB-hpcEwRJN2yFqYjtOwx-UKqs=:`) messages are delivered...even though the client hasn't acked the first one (`gAAAAABXcP9EZGOsG4N1QR2oemy8I_0ieams0UadNQAGeANbkJzK8DVCALbWbQft1quhGNu8VjlEH9066fbgvJcMJ-JWyiCA21r6O8-WxnSzqAEVqXu0wlhRgX9BBKWe4Dal5kgBEYpeUzOEubBQPvMCZZRIWnOW9cd2hucuZUC1gNVg9MyN6Hs=:`) yet.

I was expecting the second and third messages wouldn't be delivered until the first one was acked.

**Comment by jrconlin** [comment]
I believe the code is acting correctly. Since the server does not keep state when possible it delivers all pending messages except those that have been ack'd. It considers unack'd messages to be delivery failures, as if the client never received the messages.

In your case, the server repeats delivery attempt of the older messages along with newer, pending messages.

**Comment by kitcambridge** [comment]
> In your case, the server repeats delivery attempt of the older messages along with newer, pending messages.

Sorry, I didn't explain the issue well, and I think my example was misleading. The server doesn't repeat delivery of older messages. It keeps delivering new messages, even if the client hasn't acked the outstanding ones.

So, if I make 3 `PUT` requests, the server will deliver all three. My impression was that it would deliver the first, then store the other two. When I acked the first, it would deliver the second and third. If I sent any more messages, it would store them until the client acked the second and third, and so on.

**Comment by kitcambridge** [comment]
@bbangert says the limit is 10 messages, so I just didn't send enough. 😄

**Comment by jrconlin** [comment]
Posting a quick follow-up for historical purposes: 

The server will query it's database of pending, active messages and will deliver a max of 10 per attempt. The list of messages may vary due to things like TTL, priority, and other factors. The server makes no attempt to log messages that were attempted for delivery.
