### ISSUE TITLE
Services should self identify

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/autopush#50]
While working on a different project with a different service it occurred to me that we have a lot of moving parts. There are some services that exist in a "dev", "stage", "prod" or other such environment which are isolated from the others. This may be fine, or it may cause unusual issues due to information isolation (e.g. state existing in "stage" will not exist in "dev" leading to changes potentially not being properly reflected in all calls)

It would be useful for data responses to return the environment they are in as an optional component. This way, systems that may be consuming or processing results can easily confirm the source of the data that they are using and not accidentally "cross the streams".

thoughts?

**Comment by kitcambridge** [comment]
Would this be programmatic (i.e., client sends an `Accept-Environment: stage` header for HTTP and WebSocket requests; server responds with a 400 if it's running in a different environment...though, to an extent, the URI already serves that purpose)...or checked manually via `/health`?

**Comment by jrconlin** [comment]
Huh, sending as a request header is a clever idea, but I was thinking more that it's an element in the response. So since many services we have return JSON in some form, there would be an extra element like 

     {"foo":"bar", "env":"stage"}

The reason to include it in the body rather than as a return header would be because the body is going to be more visible. Headers may not be available in some cases, however the data would be. 

In my original problem, a secondary call was polling a production system. This was anomalous, but I was getting the full data response back for some calls. Having the environment self identify would have saved a good bit of effort and helped quickly determine the problem.

**Comment by crodjer** [comment]
If this isn't urgent, could I try working on it? I'll post here or on the IRC if I have any queries about this.

**Comment by jrconlin** [comment]
@crodjer yep, feel free.

Just to note: this was more the product of some wasted cycles trying to figure out what the hell was going on in a test configuration. Actually, it was a combination of test configurations (between Push, FxA and a few other systems) so it's a bit "edge case". There's no hard or fast requirement for it, but it'd be useful.
