### ISSUE TITLE
Limit HTTP request body sizes at the protocol level

### ISSUE THREAD

**Issue by kitcambridge** [mozilla-services/autopush#501]
We currently limit body sizes to 4k, but I think we check that after the entire request body has already been read.

IIUC, it's still possible for a malicious client to send gigabytes of data, which we'll buffer into memory (or a temporary file, from the looks of https://github.com/fiorix/cyclone/blob/master/cyclone/httpserver.py#L168-L179) before our request handler gets called.

**Comment by jrconlin** [comment]
This might be an odd one.

The code above relies on the data already having been read and stored in the `data` var. `data` is filled by [`lineReceived`](https://github.com/fiorix/cyclone/blob/master/cyclone/httpserver.py#L90), which is subclassed from Twisted's [`basic.LineReceiver`](https://twistedmatrix.com/documents/current/api/twisted.protocols.basic.LineReceiver.html) which may top out at [16,384](https://twistedmatrix.com/documents/current/api/twisted.protocols.basic.LineReceiver.html#MAX_LENGTH) (This might be an interesting issue for things like VAPID, but that's beside the point right now.)  The parent process reads data from the source in 65,535 byte chunks, minus the max header size,  leaves a fair bit of slop. If the `content-length` header [is specified](https://github.com/fiorix/cyclone/blob/master/cyclone/httpserver.py#L100) cyclone limits the data to that length. 

The HTTPConnection class that handles the rawDataRecieved() function is set as [a class variable](https://github.com/fiorix/cyclone/blob/master/cyclone/web.py#L1364) for Application. We could monkey patch it to reject any connection that exceeds 65K, but I'm not really sure that's a good idea. 
I'm not really sure there's a point where we can inject ourselves into that flow to, say, restrict twisted's TCP handler to only accept one 65K block. 

Continuing to dig into this.

**Comment by pjenvey** [comment]
FYI protocol class vars is a typical pattern for twisted factories. It's made for overwriting -- the preferable way is to do it is via subclassing the factory (vs monkeypatching).

**Comment by jrconlin** [comment]
Everytime I see that, I keep thinking it's more an anti-pattern. Reaching into objects directly just feels unclean. Still, if it's the expected behavior...
