### ISSUE TITLE
make build doesn't work with OSX pypy binary 

### ISSUE THREAD

**Issue by rpappalax** [mozilla-services/autopush#52]
pip missing from pypy tarball
$ make build
make: *** No rule to make target `/Users/rpappalardo/Dropbox/git/services-test/build/autopush/pypy/bin/pypy', needed by `/Users/rpappalardo/Dropbox/git/services-test/build/autopush/pypy/bin/pip'.  Stop.

**Comment by kitcambridge** [comment]
Did you download and unpack the PyPy binary into `pypy/`?

```sh
curl -sSL https://bitbucket.org/pypy/pypy/downloads/pypy-2.5.1-osx64.tar.bz2 | tar xvj
mv pypy-2.5.1-osx64 pypy
```

This is far from ideal, I know. We could automate platform detection and have it fetch the correct binary, but that will only work for platforms with pre-built packages, and won't handle updates. Still, it'll be better than nothing.

**Comment by rpappalax** [comment]
Well, shucks. i don't know why it wasn't working before and it is now.  Good enough.
Thanks, Kit!
