### ISSUE TITLE
Raise an exception in db methods missing conditional bindings

### ISSUE THREAD

**Issue by bbangert** [mozilla-services/autopush#528]
AWS will raise a ValidationError if an expression condition binds an argument that isn't included. register_user has this issue, likely from a GCM related call in endpoint.py as we had the error raised on stage at exactly the same time as a GCM error.

To ensure we don't miss arg's like this again, in addition to verifying endpoint.py is always passing them, all db methods in db.py should raise an Exception if they use a bounded expression condition for a variable that isn't in the object being passed in.

**Comment by jrconlin** [comment]
db.py register_user is wrapped with a try handler, but it only catches ConditonalCheckFailedException. This exception should propagate up. To mitigate the problem sentry notes with registration, we can have register_user return early if "router_type" or "connected_at" are not specified. This would preserve existing behavior.

Resolving endpoint call logic.

**Comment by jrconlin** [comment]
closed w/ https://github.com/mozilla-services/autopush/pull/532
