### ISSUE TITLE
Cleanup senderid_list remnants

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/autopush#544]
Most of the internal senderid_list usage (besides parsing it into senderIDs) is cruft leftover from probably from the old senderids.py module, among other things.

**Comment by jrconlin** [comment]
Careful with this one. We don't want ops changing arguments in the config files if they don't have to,  and GCM eventually is going to go away. Still, if there are instances of multiple sender_id handling that we can kill off, yes please.
