### ISSUE TITLE
Ensure router_type is present in _router_completed

### ISSUE THREAD

**Issue by bbangert** [mozilla-services/autopush#549]
A previous PR fixed the return handing in _router_completed, this fix was not applied to the _router_completed in web/webpush.py however.

**Comment by jrconlin** [comment]
The problem is that "router_type" is being mistakenly deleted from UAID information, this would cause endpoints to potentially lose routing, since each router type would define how messages should be delivered. 9e3fedbefcfc3b35863020281f4eaadb2453fee2 only partially fixed all paths.
