### ISSUE TITLE
Add a TTL header for incoming messages

### ISSUE THREAD

**Issue by kitcambridge** [mozilla-services/autopush#56]
The Web Push spec defines a `TTL` header for app servers to specify message retention duration. Setting `TTL: 0` indicates a message is ephemeral, and can be dropped immediately if the client is disconnected. This feature was requested by the Loop team to match the current Loop Push behavior, so let's add it to Simple Push.

DynamoDB doesn't support TTLs, but we can work around this by storing the expiration time and dropping expired messages when the client reconnects. We can also specify a `TTL` header in the response with the actual time-to-live...so, if an app server sends too many updates, we can indicate we're dropping messages via `TTL: 0`.

The Web Push spec also says that an omitted `TTL` is equivalent to `TTL: 0`. This could be a back-compat issue for us, since the current behavior is to store messages if the client is disconnected. OTOH, I like that storing messages requires an explicit opt-in, so it'd be nice to make this change while we have few users.

**Comment by kitcambridge** [comment]
Depends on #57; @bbangert pointed out that we don't currently have the concept of a message stream, so a TTL doesn't make sense. A simple `store=false` param in the body should be sufficient.

**Comment by bbangert** [comment]
Implementation plan:

- [ ] Add TTL field capture to endpoint.py.
- [ ] Add global index to Message table to easily locate expired messages.
- [ ] Add TTL storage to store_notification.
- [ ] Don't store message if TTL is 0 or missing.
- [ ] Add TTL check to websocket.py to avoid delivering expired messages.
- [ ] Add tests to verify TTL capture in endpoint
- [ ] Add tests to verify no delivery of expired messages
- [ ] Correlated ticket for smoke-test suite: https://github.com/mozilla-services/simplepush_test/issues/4
