### ISSUE TITLE
Remove the wsaccel dependency on PyPy

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/autopush#560]
wsaccel's a Cython accelerator for CPython for "per-byte processing" of utf8 validation/xor masking. PyPy likely JITs the pure Python ops well enough (some older benchmarks https://twistedmatrix.com/pipermail/twisted-python/2013-October/027561.html). Going through Cython (thus the CPython ext API) could be slower if anything on PyPy.

It also causes test failures in test_integration due to a CPython extension API incompatibility (arrays not supporting the buffer interface).

**Comment by pjenvey** [comment]
This means we would really need a pypy-test-requirements.txt too

**Comment by bbangert** [comment]
PR #683 didn't close this?

**Comment by pjenvey** [comment]
it's still an issue in the test requirements, so we really need a pypy-test-requirements.txt

**Comment by oberstet** [comment]
FWIW, Autobahn for quite some time does not install wsaccel when running on PyPy when doing a `pip install autobahn[accelerate]` - see [here](https://github.com/crossbario/autobahn-python/blob/master/setup.py#L79).

> This is a general thing: we try to avoid any native code library on PyPy (in Crossbar.io for example). Not only because PyPy does such an incredible job performance wise, but also because we've been bitten by memory leaks and crashes resulting from badly written native extensions.

For small payloads, PyPy is doing an incredible job JITting. For larger payloads, Autobahn WebSocket processing will run hot in the XOR masking and UTF8 validation paths CPU wise. We (Crossbar.io GmbH, formerly Tavendo GmbH) have a native, vectorized SIMD implementation of this stuff interfaced via cffi for PyPy. This is using C++ compiler intrinsics ... 

I remember @bbangert mentioned that in Mozilla's autopush deployment, you are memory-bound, not CPU bound? An probably you have smaller payloads anyway, so it doesn't matter that much. Regarding memory consumption, we track this here https://github.com/crossbario/autobahn-python/issues/640

Ah, btw, Ben, what's the current scale of your deployment in terms of number of connections? Curious;)

**Comment by pjenvey** [comment]
@oberstet, thanks for chiming in. Your cffi interfaced accelerator sounds great, is it publicly available? =]

We're currently doing around 2-3 million websocket connections and expecting a good deal more in the not to distant future

**Comment by oberstet** [comment]
@pjenvey The accelerator is closed-source, part of our commercial version of Crossbar.io.

**Comment by pjenvey** [comment]
Unfortunately the autobahn[accelerate] extra doesn't totally solve this for us. The wheel METADATA ends up hardcoding the wsaccel dependency because it was built on CPython.

That can actually be avoided w/ wheel's PEP 426 style conditional dependencies:

https://wheel.readthedocs.io/en/latest/#defining-conditional-dependencies

It'd look something like:

        "accelerate": [],
        "accelerate:'CPython' in platform_python_implementation and sys_platform != 'win32'": "wsaccel>=0.6.2",

so we'll need separate requirements files for now
