### ISSUE TITLE
Add WebPush style individual message delivery w/data

### ISSUE THREAD

**Issue by kitcambridge** [mozilla-services/autopush#57]
Modify the architecture to store individual messages with payload

# Implementation Plan

To retain efficient message delivery and storage, a separate router and db table is needed for storing individual messages. Our current router table has some space to store arbitrary additional data, but in this case we need to know in advance whether the channel exists or not, to avoid storing lots of arbitrary data that may be for expired/unregistered channels.

This first version will have a new table, keyed by hash/range key: uaid-channel_id / timestamp

Using a channel_id of "" combined with uaid will return a structure with a 'channels' field that has all registered channels.

After the router lookup indicates to use individual message delivery, the individual message router will verify the channel id is valid, and deliver/store it as needed.

## Websocket Changes

The router type will be stored for the connection, so several methods can act appropriately based on whether the prior simplepush style delivery is used, or webpush style. The following methods will need to be modified to toggle implementation based on router_type:

- register
- unregister
- process_notifications
- ack

## Database Changes & Additions

A new table for individual message storing, and all the registered channels will be added for this user.

## Router

New 'webpush router' for webpush style data retention and routing will be added.s, instead of collapsing by version.

**Comment by bbangert** [comment]
This issue will add individual message delivery, with data, to clients, along with a TTL for expiration of messages in storage.

**Comment by bbangert** [comment]
# Implementation Plan

To retain efficient message delivery and storage, a separate router and db table is needed for storing individual messages. Our current router table has some space to store arbitrary additional data, but in this case we need to know in advance whether the channel exists or not, to avoid storing lots of arbitrary data that may be for expired/unregistered channels.

This first version will have a new table, keyed by hash/range key: uaid-channel_id / timestamp

Using a channel_id of "" combined with uaid will return a structure with a 'channels' field that has all registered channels.

After the router lookup indicates to use individual message delivery, the individual message router will verify the channel id is valid, and deliver/store it as needed.

## Websocket Changes

The router type will be stored for the connection, so several methods can act appropriately based on whether the prior simplepush style delivery is used, or webpush style. The following methods will need to be modified to toggle implementation based on router_type:

- register
- unregister
- process_notifications
- ack

## Database Changes & Additions

A new table for individual message storing, and all the registered channels will be added for this user.

## Router

New 'webpush router' for webpush style data retention and routing will be added.

**Comment by jrconlin** [comment]
I presume that we can use the same basic structure for when we roll out webpush? Kinda wish that DynamoDB allowed partial hash key lookups, it would allow us to store one less row.

**Comment by bbangert** [comment]
Yup, agreed. Though at least reads are ridiculously cheap, and insane fast. So having a separate look-up to determine if the channel id is valid isn't a financial hit really. One thought was that at a future point we 'migrate' users to a separate router table that has the channel list in it or some other cheap query we can use to validate a uaid/channel_id combo before deciding to even route it.

But otherwise, we can add this now for websocket clients, and have our h2 impl. use the exact same db for a smooth migration.

**Comment by kitcambridge** [comment]
Some thoughts on the implementation:

* Let's echo the `use_webpush` flag in the `hello` reply, so the client knows that the server supports Web Push-style delivery. If the flag isn't echoed, it'll assume the server only supports vanilla Simple Push.
* If the client is offline, we'll want to extract and store the salt and record size (`rs`) from the `Encryption` header, and the Diffie-Hellman share (`dh`) from the `Encryption` header.
* We can store the body as either Base64, or binary. Transmission should probably use Base64.

So the notification packet would look like this:

```json
{
  "messageType": "notification",
  "channelID": "b0216c82-dc4d-44ca-9cec-925886074b77",
  "data": "NwrrOWPxLE8Sv5Rr0Kep7n0+r/j3rsYrUw/CXPo=",
  "salt": "uAZaiXpOSfOLJxtOCZ09dA",
  "rs": 4096,
  "dh": "BO_tgGm-yvYAGLeRe16AvhzaUcpYRiqgsGOlXpt0DRWDRGGdzVLGlEVJMygqAUECarLnxCiAOHTP_znkedrlWoU"
}
```

**Comment by bbangert** [comment]
Good point on echoing back the use_webpush flag. I'll add that.

I haven't looked over the encryption methodology yet, so I wasn't aware we needed to store anything else at all on the server-side. I thought the data was an opaque blob, and was just going to be passed along/stored.

**Comment by bbangert** [comment]
So, for simplicity, we won't process the headers. A notification packet would look like this:

```
{
  "messageType": "notification",
  "channelID": "b0216c82-dc4d-44ca-9cec-925886074b77",
  "data": "NwrrOWPxLE8Sv5Rr0Kep7n0+r/j3rsYrUw/CXPo=",
  "encryption": "keyid="dhkey"; salt="XYFSCgMVjc45IMfLOcMfiw"",
  "encryption-key": keyid="dhkey";
                   dh="BELKqvZ7n3p5C9_ipP_6X9DBNAGuJujSN7YWbtcGZMMH
                       3urZM-zlii3mGGCMjlqR-yWwiPlMdKRdOL8gQSdHw8E"
,
}
```

Of course we'll have to encode the contents of the header to deal with the double quotes, but essentially we will leave the processing of that field entirely to the client.

**Comment by bbangert** [comment]
Ok, guess we also have to retain content-encoding.

**Comment by kitcambridge** [comment]
> Of course we'll have to encode the contents of the header to deal with the double quotes, but essentially we will leave the processing of that field entirely to the client.

:+1:
