### ISSUE TITLE
Mozilla Push Server is returning a 405

### ISSUE THREAD

**Issue by ArturoWipe** [mozilla-services/autopush#575]
A user has an endpoint and receives web push. But sometimes Mozilla Push Server returns a `405` and, most of the times, the push is not sent/received.

What I know :
-     the event is sporadic, therefore cannot be reproduced
-     it can happen to a well opt-in user to push notification
-     it is not restricted to a specific Firefox version (also experienced with created enpoint from Firefox Developer Edition)
-     I only send notification without encrypted payload data (the aim is just to "wake up" the _ServiceWorker_)
-     the returned status code `405` from Mozilla Push Server is not listed in the [documentation](http://autopush.readthedocs.io/en/latest/http.html#errors)
-     nor does the response contain an `errno` label
-     most of the times in this situation, the push is not received

Have you ever experienced this ?

**Comment by ArturoWipe** [comment]
After some digging, it is more accurate to say that push is _never_ sent/received.
However, I found what could be the origin of the problem. We actually have two types of endpoint in our database:

- `https://updates.push.services.mozilla.com/push/v1/*`
- `https://updates.push.services.mozilla.com/wpush/v1/*`

After reading the response header we can see that the allowed methods are respectively:

- `Access-Control-Allow-Methods: POST,PUT`
- `Access-Control-Allow-Methods: POST`

And it happened that our `cURL` options were using a `PUT` method. After replacing it for a `POST`, the problem was solved. I presume that this specificity had been explained somewhere

**Comment by jrconlin** [comment]
Yes, the problem appears to be that you're mixing the older, out-dated "SimplePush" protocol with the new draft standard of WebPush. 

https://tools.ietf.org/html/draft-ietf-webpush-protocol-01

Our server is transitioning between the two services as the WebPush specification becomes finalized. We will continue to support existing SimplePush connections for some time, but are no longer issuing them. 

A 405 response is a HTTP standard reply indicating that the Method is not allowed. HTTP defines "Method" as the verb used when making a request, GET, POST, PUT, DELETE, OPTIONS, HEAD, etc. 
In this case, the method that returned the 405 was "PUT". 
https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

WebPush uses only "POST". WebPush specific endpoints use the "/wpush" URI path. You should still be able to send push notifications without data. As older endpoints expire, you should see more /wpush endpoints. 

As always, we look for ways to improve documentation. If there's a document you've read that hasn't been properly updated, let us know.

**Comment by ArturoWipe** [comment]
Thank you for this feedback.

Sending push notifications, without data, with WebPush specific endpoints is working well.

For now, it is hard to say what could be the "lifetime" of the older endpoints, I mean functionally. What if a user keeps this endpoint for one, two years?

**Comment by jrconlin** [comment]
Honestly, if a user kept an endpoint for that long, it would be very surprising. Endpoints are subject to change (thus the onpushsubscriptionchange events) https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/onpushsubscriptionchange . These can be triggered by any number of events, but as a subscription provider, you'd just go through the getSubscription() process again. Once you have the new endpoint you should probably drop the old endpoint and replace it with the new one.
