### ISSUE TITLE
Report invalid subscription_ids more specifically

### ISSUE THREAD

**Issue by benlast** [mozilla-services/autopush#578]
In testing error responses from autopush, we modified valid subscription endpoint URLs (e.g., `https://updates-autopush.stage.mozaws.net/wpush/v1/gAAAAABXm9zL46k0BF-HXEwueq...`) by altering one character of the last component (beginning `gAAAAA...`). The intention was to prompt a 410 GONE or 404 NOT FOUND response, specific to that token. Instead we got a 400 BAD REQUEST, with no content or other explanation.

Since there are a number of cases that can cause an "empty" (no content) 400 response (mostly meaning that the headers for the POST are not correct), our application server code isn't able to interpret the 400 as meaning the subscription_id is incorrect, so it remains in our system, eligible to have future messages sent.

It would be preferable if either the response status code were 410 or 404, or if a specific message could be included in the content to explain **why** the 400 response was generated.

**Comment by bbangert** [comment]
Indeed, the URL token failed to process, which resulted in an error in the request. As you mention though, since this is the URL failing to validate, the error should be a 410, not a 400, and a 400 should definitely have content with a errno.
