### ISSUE TITLE
Trap JWT/JWS error exceptions

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/autopush#610]
https://sentry.prod.mozaws.net/operations/autopush-prod/issues/345791/

Some non-critical JWT errors are leaking into Sentry. We should trap those and just reject the submission with appropriate error codes and info.

**Comment by kitcambridge** [comment]
Gotta catch 'em all... https://github.com/mpdavis/python-jose/blob/master/jose/exceptions.py

**Comment by bbangert** [comment]
The two parent exceptions there, yup!

**Comment by jrconlin** [comment]
Looks like just one: JOSEError, All others are classed off that one.
#smallMiracles
