### ISSUE TITLE
Switch to server driven pings

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/autopush#62]
Add logic for server to send pings to client. 

1) include `"ping_interval":_seconds_` as part of "`hello`" response
2) include logic for websocket connector to send pings at a given interval.
3) if interval needs to change, send a "long form" ping message containing the new ping_interval. 

consider:
* On idle disconnect, note remote IP.
* Add logic to allow for IP block based ping interval specifications. 
* Add logic to dynamically adjust ping delays.

**Comment by bbangert** [comment]
Do we still need this with our adaptive pings? That is, does it make sense to extend the simplepush protocol further and do more client work, or tolerate what exists now, and focus on having this done 'right' for webpush?

**Comment by jrconlin** [comment]
No longer valid.
