### ISSUE TITLE
create a base requirements file

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/autopush#625]
We should kill the duplication of requirements file dependencies by putting them all in a base requirements file. Other req files can source it w/ a **-r base** line.

I'm also tempted to move them all into a requirements/ dir since we have a number of them, plus a new base

**Comment by jrconlin** [comment]
Ah! so `-r` can be used multiple times. Yeah, we should absolutely have a base with just the differences in add on files.

**Comment by jrconlin** [comment]
This bug is causing readthedocs to fail to properly build docs.

**Comment by pjenvey** [comment]
#560 somewhat related
