### ISSUE TITLE
Bugfix: Disconnect dupe uaid's, sweep all connections for excessive idle

### ISSUE THREAD

**Issue by bbangert** [mozilla-services/autopush#65]
On connect, we should sendClose any prior client connection of the same UAID.

Also, we should have a separate task scheduled, that sweeps through *all* the connections, and if the last ping was more than N minutes/seconds ago, initiates a server-side ping......

OR.....

We turn on autobahn's websocket auto-ping feature.

**Comment by jrconlin** [comment]
Got the code working. Trying to get the tests properly mocked and all the various other PRs merged in.

**Comment by bbangert** [comment]
![show me the money!](http://i.giphy.com/3oEdv22bKDUluFKkxi.gif)
