### ISSUE TITLE
200 OK response from Autopush

### ISSUE THREAD

**Issue by pinarx** [mozilla-services/autopush#651]
When sending a message, Autopush responds with 200 instead of 201 and a "Message Sent".

 curl -v "https://updates.push.services.mozilla.com/wpush/v1/gAAAAA..." --request POST --header "TTL: 60" --header "Content-Length: 0"

**Comment by kitcambridge** [comment]
Ouch. This is a Web Push URL (`/wpush`), but it's getting a Simple Push response (based on the 200 and `Message Sent` string). We default to Simple Push in https://github.com/mozilla-services/autopush/blob/master/autopush/endpoint.py#L500, so maybe the router record is corrupt or incomplete?

**Comment by bbangert** [comment]
The /wpush/ goes to the new refactored code, it doesn't touch endpoint.py at all.

**Comment by bbangert** [comment]
This is a GCM user, the gcm.py code returns a 200 with this message. That's clearly wrong as it should be returning a 201 per WebPush.
