### ISSUE TITLE
Create unified router test suite

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/autopush#654]
We should have a consistent test suite for the routers, much like the integration tests. This would run all of the routers through a standard set of functions to ensure consistency in how they are called, and the values that they return. This would help track and prevent anomalies like #651 etc.

**Comment by jrconlin** [comment]
May block until after pjenvey's refactor work done.

**Comment by bbangert** [comment]
Any update on this? Is this a 'nice to have' or a 'must have'?

**Comment by jrconlin** [comment]
This is a "nice to have". There are some discrepancies between the router types that could be lost when finding a common form, and there are still the issues around end-to-end requiring physical devices. 

We can shelve this for now.

**Comment by bbangert** [comment]
Ok, closing for now. If/when we move the endpoint to Rust, we'll likely do this differently as well.
