### ISSUE TITLE
APNs bridge needs to allow multiple key pairs

### ISSUE THREAD

**Issue by kitcambridge** [mozilla-services/autopush#655]
Our APNs bridge only allows one key pair to be specified, but we have a different pair for each release channel: "Fennec", "Firefox", and "FirefoxBeta". I think we'll want something similar to the GCM bridge, which allows us to specify multiple sender IDs.

We currently ignore the `{app_id}` for APNs, so we can use that to determine the right key pair (for example, the URL would be `POST /v1/apns/FirefoxBeta/registration`). We can store that app ID in the router record, change the bridge config to accept multiple pairs, and have the router create an APNs client for each pair.

**Comment by jrconlin** [comment]
Huh, interesting. APNs ties a cert pair to the APNs channel it uses to communicate out. I had presumed that each platform (dev/stage/prod) would have it's own cert pair that it would use, but there's little reason we couldn't have this sort of division as well. I'd be concerned that we hit a problem similar to the senderID one, where an APNs channel uses the wrong identifier (e.g. a "prod" version uses "stage" or some similar problem).

**Comment by kitcambridge** [comment]
Right, it's tricky because there's a matrix, and they don't move in lockstep: the server has dev, stage, and prod environments; the client has Nightly, Beta, and Release channels.
