### ISSUE TITLE
use flake8-isort

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/autopush#684]

**Comment by pjenvey** [comment]
Currently blocked on better support of our import styles (and the development on this flake8 plugin seems stalled)

**Comment by pjenvey** [comment]
isort now has better support for our import styles and the flake8 plugin has recent development activity. Leaving this open because integrating this isn't too difficult, we might still get around to it

**Comment by bbangert** [comment]
No real need to get to this given the remainder of the Python code is going to move relatively soon.
