### ISSUE TITLE
further refine Handler validation

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/autopush#695]
Improvements we can do here:

o how we pass validation results to handlers. @threaded_validate currently attaches valid_input to the handler obj yet continues calling the handler method w/ unvalidated kwargs (which we always ignore and are thus confusing/dangerous to even keep around).

We should probably pass **valid_input as the kwargs instead

o We can also pass thru richer objects (like a fully constructed WebPushNotification object for e.g. in web/message.py). Either as fields.Raw or in a @post_load (not clear to me yet what works better)?

**Comment by jrconlin** [comment]
I'd prefer if we used `fields.Raw`. passing back as part of `@post_load` feels too "magical" for my tastes. We declare the fields at the top of the class and should stick to that so we don't lose data.

**Comment by pjenvey** [comment]
While shaking this out it seemed like @post_load is maybe more appropriate (webpush.py already uses it). fields.Raw would require the @post_load type code to live inside of the @validates_schema methods most of the time (and we already have some larger ones).

Almost tempted to document what the schema produces to the handler in schema class docstring to make it very clear
