### ISSUE TITLE
JSONResponseError: 400 Bad Request

### ISSUE THREAD

**Issue by bbangert** [mozilla-services/autopush#703]
Occasionally requests have a token error, these should be caught since they're not addressable bugs.

Most likely in track_provisioned so they can be logged out appropriately for ops to look at if desired.

See: https://sentry.prod.mozaws.net/operations/autopush-prod/issues/358013/

**Comment by pjenvey** [comment]
Updated sentry link: https://sentry.prod.mozaws.net/operations/autopush-prod/issues/358260/

**Comment by pjenvey** [comment]
I see sentry entries for db calls: all_channels, fetch_messages,  fetch_notifications, register_user

These come from websocket. endpoint/web.base already traps the parent BotoServerError

track_provisioned should increase a metric and reraise, then websocket can handle as it likes

**Comment by pjenvey** [comment]
actually any db call can trigger this

https://sentry.prod.mozaws.net/operations/autopush-prod/issues/360478/
