### ISSUE TITLE
Add mypy compatible type hints

### ISSUE THREAD

**Issue by bbangert** [mozilla-services/autopush#712]
We should add mypy compatible type hints throughout the code-base.

**Comment by abdulhannanali** [comment]
@pjenvey @bbangert  Haven't done python but would :heart: to take a shot on this. Is this still available?

**Comment by bbangert** [comment]
@abdulhannanali we have added some slowly over time as we go through code, but yes, this is still available as its lacking in many places. I believe @pjenvey has a large refactor of settings/config stuff, so probably want to stay out of that spot for now.

**Comment by pjenvey** [comment]
With some effort we could get mypy's tox run succeeding sooner rather than later by building on wsanchez's shell script:

https://github.com/burningmantech/ranger-ims-server/blob/master/bin/mypy

**Comment by jrconlin** [comment]
and then there are all the fun dynamically created classes that boto3 brings to the party...

**Comment by bbangert** [comment]
Closing this as it isn't a priority for maintenance mode and we can add types as it comes up in existing work.
