### ISSUE TITLE
JSONResponseError: 400 Bad Request part 2

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/autopush#744]
Follow up to #703. *Any* db call can trigger these, so we need to handle it in more cases. Here's one triggered from a router:

https://sentry.prod.mozaws.net/operations/autopush-prod/issues/369293/

We need a fix similar to https://github.com/mozilla-services/autopush/pull/718 covering other db calls

**Comment by bbangert** [comment]
Most recent example:
https://sentry.prod.mozaws.net/operations/autopush-prod/issues/379820/

Solution that I'll submit handles JSONResponse as Provisioned error, as either way the system is not accepting the db call.
