### ISSUE TITLE
Improve throughput by serving `PUT {push_endpoint}` over HTTP2

### ISSUE THREAD

**Issue by ofavre** [mozilla-services/autopush#760]
Twisted v16.3 has with HTTP2 support, as of today autopush uses v16.4 but does not support it.

From what I've read [online](https://pawelmhm.github.io/python/twisted/http2/python3/2016/07/30/twisted-http2.html) after a quick search:

> HTTP2 is not available by default, to get it you need to install hyper-h2 (just run `pip install twisted[h2]`).

As your server is already using HTTPS, that should be the only change required.

You may want to adjust `MAX_CONCURRENT_STREAMS`. As of hyper-h2 v2.5.0, [it defaults to 100](https://github.com/python-hyper/hyper-h2/blob/v2.5.0/h2/connection.py#L353).
FCM uses 100. Apple uses 500 but says they adjust the setting on the fly depending on load.

Though I am personally interested primarily in the notification sending speed, HTTP2 will likely benefit to all endpoints, and header compression might improve the network exchanges overall.

**Comment by jrconlin** [comment]
There are a few non-technical (or at least, non-code related) reasons we're holding off on providing HTTP2 support quite yet. We do want to move to offering HTTP2, and will do so as soon as we can. 

Thanks!

**Comment by bbangert** [comment]
Our current deployment setup goes through ELB's and nginx for 410 caching, so it's not quite suitable for H/2.
