### ISSUE TITLE
Partner endpoint: status endpoints must be available without providing a client certificate

### ISSUE THREAD

**Issue by oremj** [mozilla-services/autopush#771]
cc: @pjenvey

**Comment by pjenvey** [comment]
The log_check/status/health APIs do currently work with any client cert, authorized *or* unauthorized. But indeed, they should also be allowed without a cert entirely so they're as easy to use as on a regular endpoint

**Comment by oremj** [comment]
Yeah, unfortunately I can't supply a client cert for ELB health checks.
