### ISSUE TITLE
Clarify migration process to VAPID

### ISSUE THREAD

**Issue by collimarco** [mozilla-services/autopush#796]
At Pushpad we have many projects with thousands of recipients. The projects don't use VAPID at the moment. **Now I would like to introduce VAPID, without breaking existing subscriptions.**

This means that the call to `pushManager.subscribe` will now have a new `applicationServerKey` param. However the subscriptions generated in the past aren't associated to an `applicationServerKey `.

For Chrome I can look at the host of the endpoint (`fcm.googleapis.com` vs `android.googleapis.com`) in order to distinguish the endpoints for which I must use VAPID from those which don't need VAPID (I mean, when I send the notifications from the server).

For Firefox, 

1. **Is there any way to distinguish endpoints that use VAPID from the others?**, or...
2. **Can I include the VAPID headers (when I make a POST to the endpoint) even if the endpoint doesn't use VAPID** (i.e. the endpoint was generated with a call to  `pushManager.subscribe` without an `applicationServerKey ` param)? Will I get exceptions or that headers will be simply ignored?

**Comment by kitcambridge** [comment]
Hi @collimarco!

> 1. **Is there any way to distinguish endpoints that use VAPID from the others?**, or...

Yes. Subscriptions with an `applicationServerKey` have `/wpush/v2/` in the endpoint; `/wpush/v1/` without. We can change the endpoint format at any time, though, so we'd prefer if you didn't do that.

But you shouldn't need to worry about this, anyway, because...

> 2. **Can I include the VAPID headers (when I make a POST to the endpoint) even if the endpoint doesn't use VAPID** (i.e. the endpoint was generated with a call to  `pushManager.subscribe` without an `applicationServerKey ` param)?

Yes. It's perfectly OK to include VAPID headers for subscriptions without an `applicationServerKey`. We encourage you to do that for all your subscriptions.

**Comment by collimarco** [comment]
> Yes. It's perfectly OK to include VAPID headers for subscriptions without an applicationServerKey. We encourage you to do that for all your subscriptions.

Ok great! Then we'll include VAPID headers for all the subscriptions, even for those generated without an applicationServerKey. Thank you for the quick reply!

BTW It would be great to have test coverage for this behavior if not already present

**Comment by jrconlin** [comment]
Resolved.
