### ISSUE TITLE
End server support for SImplePush

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/autopush#799]
Simplepush is no longer supported and is not actively being used in field. Requirements for simplepush compatibility restrict improvements and advancements for WebPush. It is in the projects best interest to officially drop support for the long obsolete tech.

**Comment by jrconlin** [comment]
Intent to Disable note sent to dev planning

https://groups.google.com/forum/#!topic/mozilla.dev.planning/7jdtLa5JMko

**Comment by bbangert** [comment]
According to our docs, we will be supporting SimplePush through Q1/2018.
