### ISSUE TITLE
Change the `aps` block for APNs push notifications

### ISSUE THREAD

**Issue by jhugman** [mozilla-services/autopush#910]
Currently, push notifications have a payload which has an `aps` block property:

```json
{
    "aps": {
         "content-available": 1
    }
}
```

Following [experiments by the iOS team][1], the minimal block that will ensure delivery is:

```json
{
  "aps": {
      "mutable-content": 1,
      "alert": {
          "title": " ",
          "body": " "
      }
  }
}
```

Please could you change the stage and production instance of autopush to use this block?

Thanks! Love, 

The iOS team!

[1]: https://bugzilla.mozilla.org/show_bug.cgi?id=1364403

**Comment by jrconlin** [comment]
Discussion with team in channel may result in just changing the default behavior for now, and allowing the `aps` modification for the dev platform.
