### ISSUE TITLE
Consider using Toasted Marshmallow to speed up Marshmallow

### ISSUE THREAD

**Issue by rowillia** [mozilla-services/autopush#990]
Howdy!

I'm an engineer at Lyft and we just open sourced a library that speeds up Marshmallow serialization 10X (even for PyPy) - https://github.com/lyft/toasted-marshmallow .  We'll use the same technique for deserialization soon.

So sorry for the random issue, but I was talking with @pjenvey about this project a while back at a meetup and I don't have another way to contact him.

**Comment by pjenvey** [comment]
Thanks for the heads up, Roy! Great that it's a separate package now since marshmallow's reluctant to include it.

autopush is currently only using it for deserialization, so looking forward to that landing.

**Comment by pjenvey** [comment]
Roy's now implemented deserialization (https://github.com/lyft/toasted-marshmallow/pull/7)

**Comment by bbangert** [comment]
Obsolete per Rust move this year.
